### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by stclouds** [omkarcloud/omkar-temp-mail#1]
Hi. I am really appriciate for your projects. My code is 
### 
from omkar_temp_mail import TempMail

domains = TempMail.get_domains()
print(domains) 

email = "emine@1secmail.com"
link = TempMail.get_email_link(email)
print(link) 

and that is a print code 

['1secmail.com', '1secmail.org', '1secmail.net', 'icznn.com', 'ezztt.com', 'vjuum.com', 'laafd.com', 'txcct.com']
No messages
Traceback (most recent call last):
  File "C:\Users\Windows\Desktop\bot\hotmail\omkar-temp-mail-master\omkar_temp_mail\temp_mail.py", line 35, in retry_if_is_error
    created_result = func()
                     ^^^^^^
  File "C:\Users\Windows\Desktop\bot\hotmail\omkar-temp-mail-master\omkar_temp_mail\temp_mail.py", line 134, in run
    assert False
AssertionError
Retrying

**Comment by Chetan11-dev** [comment]
It's fine and retrying
